trigger:
- main
stages:
- stage: Deploy
  displayName: Deploy stage
  jobs:
  - job: Deploy
    displayName: Deploy
  - deployment: testDeploy
    displayName: Production
    environment:
      name: azure-devops-test					
      resourceType: VirtualMachine
    strategy:
      runOnce:
        deploy:
          steps:
          - script: |
             cd /var/www/html/
             sudo git clone https://github.com/nidhi8891/devops_test.git
             
             cd /var/www/html/sdk/
             sudo git clone --branch sdk https://github.com/nidhi8891/devops_test.git
