trigger:
- main
stages:
- stage: Deploy
  displayName: Deploy stage
  jobs:
  - job: Deploy
    displayName: Deploy
  - deployment: testDeploy
    displayName: Production
    environment:
      name: azure-devops-test					
      resourceType: VirtualMachine
    strategy:
      runOnce:
        deploy:
          steps:
          - script: |
             cd /var/www/html/devops_test/
             sudo git reset --hard
             sudo git checkout main
             sudo git pull

             
             cd /var/www/html/sdk/devops_test/
             sudo git reset --hard
             sudo git checkout sdk
             sudo git pull
